# mypy global options:

[project]
name = "geohashing_ds"
version = "0.1"
dependencies = [
    "numpy",
    "pandas",
]


[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

